name: Create Draft Release on Staging Merge

on:
  push:
    branches:
      - staging

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract changelog content
        id: changelog
        run: |
          # Extract the top version heading
          version=$(grep -m1 '^## ' CHANGELOG.md | sed 's/^## //')
          echo "Version found: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

          # Extract lines under the top version block
          awk '
            /^## / {
              if (seen++) exit;
              next;
            }
            seen == 1 { print }
          ' CHANGELOG.md > body.txt

          # Remove trailing empty lines from the end of the file
          perl -0777 -pe 's/\n+\z//' body.txt > trimmed.txt && mv trimmed.txt body.txt

          echo "Extracted changelog body:"
          cat body.txt

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          name: ${{ steps.changelog.outputs.version }}
          body_path: body.txt
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
